---
- name: Get repo key
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present
  become: yes

- name: Add github cli repo
  ansible.builtin.apt_repository:
    # repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    filename: gh
    state: present
  become: yes

- name: Install github cli repo
  ansible.builtin.apt:
    name: gh
    update_cache: yes
  become: yes
