- name: get repo key
  #shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes

- name: add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker
  become: yes

- name: install docker
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - docker-ce
  become: yes

- name: add user to group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes
  become: yes

- name: create /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: create daemon.json
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
  become: yes

- name: create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'
  become: yes


# - name: Install docker-compose
#   get_url:
#     url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
#     dest: /usr/local/bin/docker-compose
#     mode: '0755'
#     validate_certs: false
#   become: yes

#- name: Install docker-compose
#  shell:
#    cmd: 'wget https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64 --no-check-certificate'
#    chdir: /usr/local/bin/

- name: restart docker service
  systemd:
    name: docker
    state: restarted
  become: yes
  when: '"WSL" not in ansible_kernel'

- name: install dive
  apt:
    deb: https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
    state: present
  become: yes

