---
- name: Install ansible utils
  ansible.builtin.pip:
    name:
      - ansible-lint
      - yamllint
  become: yes

- name: Config ansible.cfg
  ansible.builtin.template:
    dest: "{{ lookup('env', 'HOME') }}/.ansible.cfg"
    src: ansible.cfg.j2
  become: yes

- name: Config vimrc
  ansible.builtin.template:
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
    src: vimrc.j2
