- name: Config repos
  apt_repository:
    repo: deb https://deb.debian.org/debian stretch-backports main
    state: present
  become: yes

- name: install deps
  apt:
    name: "{{ item }}"
    cache_valid_time: 600
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python3-pip
  become: yes
