- name: add dns servers
  lineinfile:
      path: /etc/dhcp/dhclient.conf
      regexp: "^prepend domain-name-servers"
      line: "prepend domain-name-servers {{ dns_servers | default(8.8.8.8) }};"
  become: yes
