---
- name: Get repo key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes

- name: Add packer repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    filename: kubernetes
    state: present
  become: yes

- name: Install packer
  ansible.builtin.apt:
    name: packer
    update_cache: yes
  become: yes
